language: cpp
sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode9.3
  - os: osx
    osx_image: xcode8.3
before_install:
- uname -a; sw_vers
install:
- export HOMEBREW_NO_AUTO_UPDATE=1
- brew tap heavywatal/tap
- brew install sfmt-class cxxwtl
script:
- mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
- cmake --build . -- --jobs=2
- cmake --build . --target install
- ctest -V
notifications:
  email: false
